# Generated by Django 5.2 on 2025-06-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_carrito_options_carrito_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado_pago',
            field=models.CharField(choices=[('cart_active', 'En Carrito (activo)'), ('in_process', 'Pago en Proceso (MP)'), ('pending', 'Pendiente (MP)'), ('approved', 'Aprobado (MP)'), ('rejected', 'Rechazado (MP)'), ('cancelled', 'Cancelado (MP)'), ('refunded', 'Reembolsado (MP)')], default='cart_active', max_length=20, verbose_name='Estado del Pago'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Compra Efectiva'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_pago_actualizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización Pago'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Salida del Viaje'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='mercadopago_external_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Referencia Externa MP'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Pago MP'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Preferencia MP'),
        ),
    ]
